using TestLibrary;

namespace GeneratedTests
{
    public class AutoGeneratedTests
    {
        public void Test_Test1_Add()
        {
            var instance = new TestLibrary.Test1();
            instance.Add(0, 0);
        }

        public void Test_Test1_Divide()
        {
            var instance = new TestLibrary.Test1();
            instance.Divide(0.0, 0.0);
        }

        public void Test_Test1_Echo()
        {
            var instance = new TestLibrary.Test1();
            instance.Echo("test");
        }

        public void Test_Test1_PrintHello()
        {
            TestLibrary.Test1.PrintHello();
        }

        public void Test_Test1_Hidden()
        {
            var instance = new TestLibrary.Test1();
            instance.Hidden();
        }

        public void Test_Test2_ReturnString()
        {
            var instance = new TestLibrary.Test2();
            instance.ReturnString();
        }

        public void Test_Test2_RaiseEvent()
        {
            var instance = new TestLibrary.Test2();
            instance.RaiseEvent();
        }

        public void Test_Test3_Overload()
        {
            var instance = new TestLibrary.Test3();
            instance.Overload();
        }

        public void Test_Test3_Overload()
        {
            var instance = new TestLibrary.Test3();
            instance.Overload(0);
        }

        public void Test_Test3_Overload()
        {
            var instance = new TestLibrary.Test3();
            instance.Overload("test");
        }

        public void Test_Test3_Identity()
        {
            var instance = new TestLibrary.Test3();
            instance.Identity(null);
        }

        public void Test_Test4_StaticMethod()
        {
            TestLibrary.Test4.StaticMethod();
        }

        public void Test_Test5_RefOutMethod()
        {
            var instance = new TestLibrary.Test5();
            instance.RefOutMethod(null, null);
        }

        public void Test_Test5_SumParams()
        {
            var instance = new TestLibrary.Test5();
            instance.SumParams(null);
        }

        public void Test_Test6`1_GenericMethod()
        {
            var instance = new TestLibrary.Test6`1();
            instance.GenericMethod(null);
        }

        public void Test_Test6`1_StaticGenericMethod()
        {
            TestLibrary.Test6`1.StaticGenericMethod(null);
        }

        public void Test_Test7Impl_InterfaceMethod()
        {
            var instance = new TestLibrary.Test7Impl();
            instance.InterfaceMethod();
        }

        public void Test_Test8Base_AbstractMethod()
        {
            var instance = ;
            instance.AbstractMethod();
        }

        public void Test_Test8Base_VirtualMethod()
        {
            var instance = ;
            instance.VirtualMethod();
        }

        public void Test_Test8Derived_AbstractMethod()
        {
            var instance = new TestLibrary.Test8Derived();
            instance.AbstractMethod();
        }

        public void Test_Test8Derived_VirtualMethod()
        {
            var instance = new TestLibrary.Test8Derived();
            instance.VirtualMethod();
        }

        public void Test_<>c_<.ctor>b__4_0()
        {
            var instance = new TestLibrary.Test2+<>c();
            instance.<.ctor>b__4_0(new object(), null);
        }

        public void Test_<>c_<.ctor>b__5_0()
        {
            var instance = new TestLibrary.Test2+<>c();
            instance.<.ctor>b__5_0(new object(), null);
        }

    }
}
