using RandoopMain;
using System.Text;

namespace TestGenerator
{
    public class TestGenerator
    {
        public static void GenerateTests(string dllPath, string outputPath)
        {
            var reflectedClasses = DllCollector.Collect(dllPath);
            var sb = new StringBuilder();

            sb.AppendLine("using System;");
            sb.AppendLine("using TestLibrary;");
            sb.AppendLine();
            sb.AppendLine("namespace GeneratedTests");
            sb.AppendLine("{");
            sb.AppendLine("    public class AutoGeneratedTests");
            sb.AppendLine("    {");

            foreach (var rClass in reflectedClasses)
            {
                string typeName = rClass.FullName;
                string simpleName = rClass.SimpleName;
                string instanceExpr = "";
                if (rClass.CanInstantiate)
                {
                    instanceExpr = $"new {typeName}()";
                }

                foreach (var method in rClass.Methods)
                {
                    string testName = $"Test_{simpleName}_{method.Name}";

                    sb.AppendLine("        public void " + testName + "()");
                    sb.AppendLine("        {");

                    if (!method.IsStatic && instanceExpr != null)
                    {
                        sb.AppendLine($"            var instance = {instanceExpr};");
                    }

                    var callArgs = string.Join(", ", method.ParameterTypes.Select(GetDummyArg));

                    string callTarget;
                    if (method.IsStatic)
                    {
                        callTarget = typeName;
                    }
                    else
                    {
                        callTarget = "instance";
                    }

                    sb.AppendLine($"            {callTarget}.{method.Name}({callArgs});");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(outputPath, sb.ToString());
            Console.WriteLine("Test file generated at: " + outputPath);
        }

        private static string GetDummyArg(Type type)
        {
            if (type == typeof(int)) return "0";
            if (type == typeof(double)) return "0.0";
            if (type == typeof(string)) return "\"test\"";
            if (type == typeof(bool)) return "false";
            if (type == typeof(object)) return "new object()";
            if (type.IsValueType) return $"default({type.Name})";
            return "null";
        }
    }
}
